// Re-exportar todo desde la carpeta rules
export {
  createGame,
  resetGame,
  getPieceMoves,
  getAllLegalMoves,
  getReserveEntries,
  applyMove,
  executeDrop,
  isPromotionAvailableForMove,
  afterMoveEvaluation,
  getBoardMeta,
  getPieceText,
  executeArcherAmbush,
  isKingInCheck,
  isSquareProtectedByArcher,
  getLegalMovesForSquare,
  isSquareAttacked,
  getLegalReserveDrops,
  getArcherAmbushResult,
  moveWouldPromote,
  isDropLegal,
  isPalaceCursedFor,
  getPalaceInvaders,
} from './core.js';
